In [1]:
print('hello world')

hello world

a= "hello"
b= 22
d= a+str(b)
print(d)

In [2]:
a="hello"
b=22
d= a + str(b)
print(d)

hello22

In [3]:
#variable
p=int(input("enter principle:"))
t=int(input("enter time:"))
r=int(input("enter rate:"))
si=(p*t*r)/100
print("simple interest is:",si)

simple interest is: 168.0

In [5]:
name=input("enter your name:")
add=input("enter your address:")
info="hello world I am"+name+"."+ "i am from "+ add +"."
print(info)

hello world I amanshu.i am from dhobidhara.

In [ ]:
sub1=int(input("enter marks of subject 1:"))
sub2=int(input("enter marks of subject 2:"))
sub3=int(input("enter marks of subject 3:"))   
sub4=int(input("enter marks of subject 4:"))
sub5=int(input("enter marks of subject 5:"))
total=sub1+sub2+sub3+sub4+sub5
pr=total/5
print("percentage is:",pr)

percentage is: 72.0

In [ ]:
age=int(input("enter your age:"))
if age>=18:
    print("you are eligible for voting")
elif age==18:
    print("you are eligible for voting")
else:
    print("you are not eligible for voting")

you are not eligible for voting

In [1]:
a=input("Enter value of a:")
b=input("Enter value of b:")
c=a+b
print(c)

16

In [2]:
num=int(input("Enter value:"))
if num%2==0 :
    print("Number is even")
else:
    print("Number is odd")

Number is even

In [3]:
num=int(input("Enter a number:"))
if num<0:
    print("Negative Number")
else:
    print("Positive Number")

Negative Number

In [4]:
for i in range(2):
    print(i,"hello World")

0 hello World
1 hello World

In [7]:
n=int(input("Enter the value of n="))
for i in range(2,22):
    print(i*n)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21

In [8]:
a="python"
print(a[0])
print(a[0:4])
print(a[0:10:2])

p
pyth
pto

In [9]:
a="I am studying"
print(a[::-1])

gniyduts ma I

In [15]:
a="python"
l=len(a)
print(l)

i=0

while i<l:
    print(a[i],end=" ")
    i=i+1

6
p y t h o n

In [20]:
info=["python","Java","c","ruby"]
name="Java"
print(type(name))
if name in info:
    print("yes present")
    print(info.count(name))
else:
    print("no it is not present")

<class 'str'>
yes present
1

In [21]:
info="Ram Sudip Krisma Anshu Anush"
c=info.split()
print(c)

['Ram', 'Sudip', 'Krisma', 'Anshu', 'Anush']

In [22]:
a="hello"
b=10
c=a+ str(b)
print(c)

hello10

In [23]:
a=10
b=complex(a)
print(b)

(10+0j)

In [25]:
a=10
b=11
print(a!=b)
print(a==b)

True
False

In [38]:
a=int(input("Enter a number"))
b=int(input("Enter a number"))
c=(input("Enter your choice \n 1.Addition \n 2.Subtraction \n 3.Multiplication \n 4.Divide \n"))
if(c=='1'):
    print(a+b)
elif(c=='2'):
    print(a-b)
elif(c=='3'):
    print(a*b)
elif(c=='4'):
    print(a/b)
else:
    print("Enter number between 1 to 4")

5

In [42]:
a=int(input("Enter a number:"))
for i in range(1,11):
    print(str(a) + "*" +str(i) + "=",a*i)
    print(a, "*" ,i ,"=",a*i)

5*1= 5
5 * 1 = 5
5*2= 10
5 * 2 = 10
5*3= 15
5 * 3 = 15
5*4= 20
5 * 4 = 20
5*5= 25
5 * 5 = 25
5*6= 30
5 * 6 = 30
5*7= 35
5 * 7 = 35
5*8= 40
5 * 8 = 40
5*9= 45
5 * 9 = 45
5*10= 50
5 * 10 = 50

In [43]:
a=''' hlo
what's up
i am fine'''
print(a)

 hlo
what's up
i am fine

In [ ]:
#Wap to create a billing system that includes name price qty total
total = 0
i=0
while(i<2):
    a=input("Enter a name:")
    b=int(input("Enter price:"))
    c=int(input("Enter quantity:"))
    print("Name",a)
    print("Price",b)
    print("Quantity",c)
    total=total+(b*c)
    i=i+1
print("total:",total)

a,b,c
a,b,c
a,b,c
a,b,c
a,b,c
total:

In [ ]:
#Wap to create a billing system that includes name price qty total
total = 0
i=0
while(i<2):
    a=input("Enter a name:")
    b=int(input("Enter price:"))
    c=int(input("Enter quantity:"))
    print("Name",a)
    print("Price",b)
    print("Quantity",c)
    total=total+(b*c)
    i=i+1
print("total:",total)


#num=(int(input("Enter number of products:")))
#for i in range (num):
    #name=input("name of prodeuct:")
    #price=""
    #quantity=""
    #print("total cost=",total) #for bhitra garyo bhane individual total auxa

Name apple
Price 100
Quantity 2
Name banana
Price 200
Quantity 3
total: 800

In [ ]:
#list 
l=list()
a=["python","Java","c","ruby"]
print(a[0])
print(a[0:3])
print(len(a))
for i in range (len(a)):
    print(i)
    #for i in a:
    #print(i)

python
['python', 'Java', 'c']
4

In [5]:
#append()
a=list()
a.append("apple")
a.append("social")
a
#print(a)

['apple', 'social']

In [6]:
#insert
a.insert(1,"math")
a

['apple', 'math', 'social']

In [7]:
#extend
a=["python","Java","c","ruby"]
b=[1,2,3,5]
a.extend(b)
a

['python', 'Java', 'c', 'ruby', 1, 2, 3, 5]

In [8]:
num=[1,4,8,999]
print("max value",max(num))
print("min value",min(num))
print("sum value",sum(num))
num.reverse()
print(num)

max value 999
min value 1
sum value 1012
[999, 8, 4, 1]

In [9]:
#update 
a=["python","Java","c","ruby"]
a[0]="com"
a

['com', 'Java', 'c', 'ruby']

In [12]:
#update and add
a=["python","Java","c","ruby"]
a[0:2]=["Js","c++"]
a

['Js', 'c++', 'c', 'ruby']

In [14]:
#delete
a=["python","Java","c","ruby"]
#del a[0]
del a[1:3]
a

['python', 'ruby']

In [15]:
#remove
a=["python","Java","c","ruby"]
a.remove("ruby")
a

['python', 'Java', 'c']

In [18]:
#pop
a=["python","Java","c","ruby"]
#b=a.pop()
a.clear()
a

[]

In [25]:
a=[["anshu",33,"dhobidhara"],["krisma",23,"Jungle"]]
print(a[1])
print(a[0][2])
print(a[1][1])
a.append(["sudip",2,"zoo"])
a

['krisma', 23, 'Jungle']
dhobidhara
23

[['anshu', 33, 'dhobidhara'], ['krisma', 23, 'Jungle'], ['sudip', 2, 'zoo']]

In [26]:
name=[["anshu",33,"dhobidhara"],["krisma",23,"Jungle"],["sudip",2,"zoo"]]
del name[0]
name

[['krisma', 23, 'Jungle'], ['sudip', 2, 'zoo']]

In [ ]:
a=[["anshu",33,"dhobidhara"],["krisma",23,"Jungle"],["sudip",2,"zoo"]]
name=input("enter name")
found=0
for i in range (len(a)):
    if name in a[i]:
        found=found+1
if(found>=1):
    print("yes present")
else:
    print("no it is not present")

yes present

In [ ]:
#for in a:
# if name in i
#print(i)

In [ ]:
#tuple
#immutable
#define by small bracket
#no del pop()

In [39]:
a=(1,2,8,6)
print(a)

(1, 2, 8, 6)

In [40]:
a=("home","mobile","phone")
print(a[1])

mobile

In [42]:
a=(1,)
print(type(a))
b=(1)
print(type(b))

<class 'tuple'>
<class 'int'>

In [48]:
a="hello"
tuple(a)

('h', 'e', 'l', 'l', 'o')

In [49]:
b=("hello",)
list(b)

['hello']

In [50]:
#llst inside tuple
a=([1,2],[3,5],[4,6])
a

([1, 2], [3, 5], [4, 6])

In [51]:
#llst inside tuple
a=((1,2,3),(1,4,6))
a

((1, 2, 3), (1, 4, 6))

In [57]:
p=list()
n=int(input("Enter number of user"))
for i in range (n):
    a=input("Enter name:")
    #p.append(a)
    b=int(input("Enter age:"))
    #p.append(b)
    c=input("Enter address:")
    p.append((a,b,c))

print(p)

[('ansu', 20, 'bagbazar'), ('krisma', 100, 'jarankhu')]

In [59]:
a=[]
n=int(input("Enter n="))
for i in range (n):
    name=input("Enter name:")
    age=int(input("Enter age:"))
    address=input("Enter address:")
    a.append((name,age,address))
print(a)

[('anshu', 23, 'hsios')]

In [65]:
a=[]
n=int(input("Enter n="))
for i in range (n):
    name=input("Enter name:")
    age=int(input("Enter age:"))
    address=input("Enter address:")
    a.append([name,age,address])
print(a)

[['jsk', 1, 'mak']]

In [1]:
i=0
item_total=0
total=0
list=[]

while(i<5):
    a=input("Enter a Item name:")
    b=int(input("Enter price:"))
    c=int(input("Enter quantity:"))
    list.append([a,b,c])
    i=i+1
print(list)

print("\n-----------------Shopping List--------------------\n")
print("Item Name\t| \tPrice\t |\tQuantity")
print("---------------------------------------------------")

for i in range(len(list)):
    #item_total = list[i][1] * list[i][2]
    print(list[i][0], "\t\t|\t" ,list[i][1], "\t|\t" ,list[i][2])
    total=total+(list[i][1]*list[i][2])
print("---------------------------------------------------")
print("Total Cost:\n",total)

search=input("Enter item name to search:\n")
for item in list:
    if item[0] == search :
        print("\nItem Found\n")
        print("Item Name | \t Price| \t Quantity | \tTotal ")
        print(item[0], "\t|\t" ,item[1],"\t|\t",item[2],"\t|\t",item[1]*item[2])
        break
else:


    print("\nItem Not Found")

[['Apple', 50, 7], ['Banana', 45, 6], ['Kiwi', 80, 9], ['Orange', 190, 7], ['Mango', 200, 4]]

-----------------Shopping List--------------------

Item Name	| 	Price	 |	Quantity
---------------------------------------------------
Apple 		|	 50 	|	 7
Banana 		|	 45 	|	 6
Kiwi 		|	 80 	|	 9
Orange 		|	 190 	|	 7
Mango 		|	 200 	|	 4
---------------------------------------------------
Total Cost:
 3470

Item Found

Item Name | 	 Price| 	 Quantity | 	Total
Mango 	|	 200 	|	 4 	|	 800

In [1]:
#dictionary
#key value pair
#mutable
a=dict()
print(type(a))

<class 'dict'>

In [3]:
a={}  #empty dictionary
a['a']='java' 
a['b']='javascript'
print(a)

{'a': 'java', 'b': 'javascript'}

In [5]:
#key should always be unique
info={}
n=int(input('Enter n'))
for i in range(n):
    name=input('Enter name=')
    phone=int(input('Enter phone'))
    info[name]=phone
print(info)

{'ansu': 9479370, 'kjfdkd': 9381030}

In [7]:
a={'ansu':'9849128543', 'gita':'963893003'}
for i in a.items():
    print(i)

('ansu', '9849128543')
('gita', '963893003')

In [9]:
for i in a.values():
    print(i)
for i in a:
      print(i)

9849128543
963893003
ansu
gita

In [ ]:
#tuple into dict
d=(
    ("ram",19),
    ("hari",28)
)
dict(d)

{'ram': 19, 'hari': 28}

In [17]:
#update
a={'ansu':'9849128543', 'gita':'963893003'}
a['ansu']=10390031
a['9849128543']='nanu'
a

{'ansu': 10390031, 'gita': '963893003', '9849128543': 'nanu'}

In [14]:
#delete
a={'ansu':'9849128543', 'gita':'963893003'}
b=a.pop('ansu')
print(a)
print(b)

{'gita': '963893003'}
9849128543

In [19]:
a={'ansu':'9849128543', 'gita':'963893003'}
del a['ansu']
a

{'gita': '963893003'}

In [20]:
#list inside dict
info={"Name":["ram","sudip"],
      "age":[33,33],
      "address":["bagbazar","lalitpur"]}
info

{'Name': ['ram', 'sudip'],
 'age': [33, 33],
 'address': ['bagbazar', 'lalitpur']}

In [23]:
info=[
      {"name":'ansu',"address":"lalitpur"}]
info

[{'name': 'ansu', 'address': 'lalitpur'}]

In [24]:
#set
#unordered
#multiple but no duplicate data and is mutable
s={"Java","C","p","p"}
print(s)

{'C', 'p', 'Java'}

In [ ]:
#concatinate ra multiply hunnna
a={1,2,3}
b={5,3,4,4}
c = a+b
d=a*2
print(c)

TypeError: unsupported operand type(s) for +: 'set' and 'set'

In [29]:
#add()
s=set()
s.add("Mern")
s.add("react")
print(s)

{'Mern', 'react'}

In [30]:
#update
a={1,2,3}
b={5,3,4,4}
a.update(b)
print(a)

{1, 2, 3, 4, 5}

In [31]:
#remove
s={"Java","mern","raect","mern"}
s.remove("mern")
s

{'Java', 'raect'}

In [35]:
s={"Java","mern","raect","mern"}
t={"bulb","bill","sill","Java","mern"}
#intersection
a=s.intersection(t)
print(a)
#union
b=s.union(t)
print(b)
#only s
print(s-t)
#only t
print(t-s)

{'mern', 'Java'}
{'sill', 'Java', 'mern', 'bill', 'bulb', 'raect'}
{'raect'}
{'sill', 'bulb', 'bill'}

In [2]:
#create a dictionary to store student scores
info={}
n=int(input('Enter n'))
for i in range(n):
    name=input('Enter name=')
    marks=int(input('Enter marks'))
    info[name]=marks
print(info)

search=input("Enter name to search:\n")
for i in info:
    if (name==search):
        print(" Name Found")
        print(name,marks)
        break
    else:
          print("\n Name not Found\n")

scores = {}

n = int(input("Enter number of students: "))

for i in range(n):
    name = input("Enter student name: ")
    score = int(input("Enter student score: "))
    scores[name] = score

print("\nAll students and scores:")
for name, score in scores.items():
    print(name, ":", score)

search = input("\nEnter student name to check: ")

if search in scores:
    print("Score of", search, "is", scores[search])
else:
    print("Student not found")

#for key,values ab,b in a.items()

{'Ansu': 99, 'utsaa': 80, 'sudip': 29}

 Name not Found


 Name not Found


 Name not Found

ValueError: invalid literal for int() with base 10: 'dk'

In [51]:
#function
#def function_name():
    #operation
#function_name()
def display():
    print("hello world")
display()

hello world

In [53]:
def sum():
    a=10
    b=20
    c=a+b
    print("sum=",c)
sum()

sum= 30

In [54]:
#types of function
#1. No parameter, No return
def greet():    #parameter
    print("hello")
greet()     #arguments

hello

In [55]:
# A parameter is a variale in the function defination
        #It acts like a placeholder
# Arguments: An arguments is the actual you can pass when calling the function

In [1]:
#2) parameter, no return
#takes input but does not return value

def display(name):
    print("hello",name)
display("Ram")

hello Ram

In [3]:
#create a dictionary to store student scores
scores = {}

n = int(input("Enter number of students: "))

for i in range(n):
    name = input("Enter student name: ")
    score = int(input("Enter student score: "))
    scores[name] = score

print("\nAll students and scores:")
for name, score in scores.items():
    print(name, ":", score)

search = input("\nEnter student name to check: ")

if search in scores:
    print("Score of", search, "is", scores[search])
else:
    print("Student not found")

All students and scores:
ansu : 99
utsaav : 20
sudip : 17
krisma : 33
Score of krisma is 33

In [2]:
#types of function
#3) no parameter,with return
#takes nothing but gives output

def get_number():
    return 10
num=get_number()
print(num)

10

In [1]:
#4) parameter,return
#takes input returns output

def add(a,b):
    return a+b
result=add(10,20)
print("sum",result)

sum 30

In [5]:
#default parameter function
def greet(name,greeting="hello"):
    print(greeting,name)
greet("Ansu")

hello Ansu

In [6]:
#keyword arguments
def info(name,age):
    print(name,age)
info(age=22,name="Ansu")

Ansu 22

In [7]:
#lamda function(short function)
add=lambda a,b:a+b
print(add(2,3))

5

In [8]:
#variable length argument function
#args(multiple values)
def add(*numbers):
    print(sum(numbers))
add(1,2,3,4,5)

15

In [9]:
#kwargs(key -value pair)

def info(**data):
    print(data)
info(name="Ram",age=20)

{'name': 'Ram', 'age': 20}

In [ ]:
#scenario student results system
#Create a function that:
#takes marks as input
#returns "pass" or"fails"

def info(marks):
    if marks >= 40:
        return "pass"
    else:
        return "fail"
print(info(90))

pass

In [ ]:
#login system (username check)
#scenario:system checks if username is correct
#write a function that verifies username

def verify_username(username):
    if username == "Ansu":
        return True
    else:
        return False
print(verify_username("Ansu"))

True

In [15]:
def username():
    Username=input("Enter username:")
    if Username=="Ansu":
        print("Username is correct")
    else:
        print("Username is incorrect")
username()

Username is correct

In [16]:
#file
#file=open("test.txt","w")  # open(<filename>,<mode>)
#fileclose()

#with open (<filename>,<mode>) as file:
    #<operations>

#mode
#read->r
#create->x
#append->a
#write->w

In [17]:
try:
    file=open("Datas.txt","x")
    file.close()
except:
    print("File already exists")

In [1]:
file=open("Datas.txt","r")
data=file.read()
print(data)
file.close()

Hello world

In [3]:
file=open("Datas.txt","w")
file.write("hello world i am ansu\n")
file.close()

In [4]:
#csv(comma separated value)
try:
    file=open("Datas.csv","x")
    file.close()
except:
    print("File already exists")

In [12]:
import pandas as pd
df=pd.read_csv("House_Rent_Dataset.csv")
df

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner
...,...,...,...,...,...,...,...,...,...,...,...,...
4741,2022-05-18,2,15000,1000,3 out of 5,Carpet Area,Bandam Kommu,Hyderabad,Semi-Furnished,Bachelors/Family,2,Contact Owner
4742,2022-05-15,3,29000,2000,1 out of 4,Super Area,"Manikonda, Hyderabad",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Owner
4743,2022-07-10,3,35000,1750,3 out of 5,Carpet Area,"Himayath Nagar, NH 7",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Agent
4744,2022-07-06,3,45000,1500,23 out of 34,Carpet Area,Gachibowli,Hyderabad,Semi-Furnished,Family,2,Contact Agent
4745,2022-05-04,2,15000,1000,4 out of 5,Carpet Area,Suchitra Circle,Hyderabad,Unfurnished,Bachelors,2,Contact Owner

In [10]:
! pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.1-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 2.3 MB/s eta 0:00:05
   ---- ----------------------------------- 1.0/9.8 MB 2.3 MB/s eta 0:00:04
   ------ --------------------------------- 1.6/9.8 MB 2.3 MB/s eta 0:00:04
   -------- ------------------------------- 2.1/9.8 MB 2.3 MB/s eta 0:00:04
   --------- ------------------------------ 2.4/9.8 MB 2.3 MB/s eta 0:00:04
   ----------- ---------------------------- 2.9/9.8 MB 2.2 MB/s eta 0:00:04
   ------------- -------------------------- 3.4/9.8 MB 2.2 MB/s eta 0:00:03
   -------------- ------------------------- 3.7/9.8 MB 2.2 MB/s eta 0:00:03
   ----------------- ---------------------- 4.2/9.8 MB 2.1 MB/s eta 0:00:03
   ------------------- -------------------- 4.7/9.8 MB 2.1 MB/s eta 0:00:03
   -------------------- ------------------- 5.0/9.8 MB 2.1 MB/s eta 0:00:03
   ---------------------- ----------------- 5.5/9.8 MB 2.1 MB/s eta 0:00:03
   ------------------------ --------------- 6.0/9.8 MB 2.1 MB/s eta 0:00:02
   ------------------------- -------------- 6.3/9.8 MB 2.1 MB/s eta 0:00:02
   --------------------------- ------------ 6.8/9.8 MB 2.1 MB/s eta 0:00:02
   ---------------------------- ----------- 7.1/9.8 MB 2.1 MB/s eta 0:00:02
   ------------------------------ --------- 7.6/9.8 MB 2.1 MB/s eta 0:00:02
   -------------------------------- ------- 7.9/9.8 MB 2.1 MB/s eta 0:00:01
   ---------------------------------- ----- 8.4/9.8 MB 2.1 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.8 MB 2.1 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.8 MB 2.0 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 2.0 MB/s  0:00:04
Downloading numpy-2.5.1-cp313-cp313-win_amd64.whl (12.4 MB)
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.4 MB 2.2 MB/s eta 0:00:06
   --- ------------------------------------ 1.0/12.4 MB 2.0 MB/s eta 0:00:06
   ---- ----------------------------------- 1.3/12.4 MB 1.9 MB/s eta 0:00:06
   ---- ----------------------------------- 1.3/12.4 MB 1.9 MB/s eta 0:00:06
   ----- ---------------------------------- 1.8/12.4 MB 1.6 MB/s eta 0:00:07
   ------ --------------------------------- 2.1/12.4 MB 1.5 MB/s eta 0:00:07
   ------- -------------------------------- 2.4/12.4 MB 1.5 MB/s eta 0:00:07
   --------- ------------------------------ 2.9/12.4 MB 1.6 MB/s eta 0:00:07
   ----------- ---------------------------- 3.7/12.4 MB 1.8 MB/s eta 0:00:05
   --------------- ------------------------ 4.7/12.4 MB 2.1 MB/s eta 0:00:04
   ----------------- ---------------------- 5.5/12.4 MB 2.3 MB/s eta 0:00:04
   ------------------- -------------------- 6.0/12.4 MB 2.3 MB/s eta 0:00:03
   --------------------- ------------------ 6.6/12.4 MB 2.3 MB/s eta 0:00:03
   ---------------------- ----------------- 7.1/12.4 MB 2.3 MB/s eta 0:00:03
   ------------------------ --------------- 7.6/12.4 MB 2.3 MB/s eta 0:00:03
   -------------------------- ------------- 8.1/12.4 MB 2.3 MB/s eta 0:00:02
   --------------------------- ------------ 8.7/12.4 MB 2.4 MB/s eta 0:00:02
   ----------------------------- ---------- 9.2/12.4 MB 2.4 MB/s eta 0:00:02
   ------------------------------ --------- 9.4/12.4 MB 2.4 MB/s eta 0:00:02
   ------------------------------- -------- 9.7/12.4 MB 2.3 MB/s eta 0:00:02
   ------------------------------- -------- 9.7/12.4 MB 2.3 MB/s eta 0:00:02
   -------------------------------- ------- 10.0/12.4 MB 2.1 MB/s eta 0:00:02
   -------------------------------- ------- 10.0/12.4 MB 2.1 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 2.0 MB/s eta 0:00:02
   -------------------------------- ------- 10.2/12.4 MB 2.0 MB/s eta 0:00:02
   --------------------------------- ------ 10.5/12.4 MB 1.9 MB/s eta 0:00:02
   --------------------------------- ------ 10.5/12.4 MB 1.9 MB/s eta 0:00:02
   ---------------------------------- ----- 10.7/12.4 MB 1.8 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.4 MB 1.8 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.4 MB 1.8 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.4 MB 1.7 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.4 MB 1.7 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.4 MB 1.7 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.4 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.4 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 12.4/12.4 MB 1.6 MB/s  0:00:07
Using cached tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.5.1 pandas-3.0.5 tzdata-2026.3

In [16]:
print(df.head())
print(df.tail())

    Posted On  BHK   Rent  Size            Floor    Area Type  \
0  2022-05-18    2  10000  1100  Ground out of 2   Super Area
1  2022-05-13    2  20000   800       1 out of 3   Super Area
2  2022-05-16    2  17000  1000       1 out of 3   Super Area
3  2022-07-04    2  10000   800       1 out of 2   Super Area
4  2022-05-09    2   7500   850       1 out of 2  Carpet Area

              Area Locality     City Furnishing Status  Tenant Preferred  \
0                    Bandel  Kolkata       Unfurnished  Bachelors/Family
1  Phool Bagan, Kankurgachi  Kolkata    Semi-Furnished  Bachelors/Family
2   Salt Lake City Sector 2  Kolkata    Semi-Furnished  Bachelors/Family
3               Dumdum Park  Kolkata       Unfurnished  Bachelors/Family
4             South Dum Dum  Kolkata       Unfurnished         Bachelors

   Bathroom Point of Contact
0         2    Contact Owner
1         1    Contact Owner
2         1    Contact Owner
3         1    Contact Owner
4         1    Contact Owner
       Posted On  BHK   Rent  Size         Floor    Area Type  \
4741  2022-05-18    2  15000  1000    3 out of 5  Carpet Area
4742  2022-05-15    3  29000  2000    1 out of 4   Super Area
4743  2022-07-10    3  35000  1750    3 out of 5  Carpet Area
4744  2022-07-06    3  45000  1500  23 out of 34  Carpet Area
4745  2022-05-04    2  15000  1000    4 out of 5  Carpet Area

             Area Locality       City Furnishing Status  Tenant Preferred  \
4741          Bandam Kommu  Hyderabad    Semi-Furnished  Bachelors/Family
4742  Manikonda, Hyderabad  Hyderabad    Semi-Furnished  Bachelors/Family
4743  Himayath Nagar, NH 7  Hyderabad    Semi-Furnished  Bachelors/Family
4744            Gachibowli  Hyderabad    Semi-Furnished            Family
4745       Suchitra Circle  Hyderabad       Unfurnished         Bachelors

      Bathroom Point of Contact
4741         2    Contact Owner
4742         3    Contact Owner
4743         3    Contact Agent
4744         2    Contact Agent
4745         2    Contact Owner

In [18]:
df=pd.read_csv("House_Rent_Dataset.csv", index_col=['BHK'])
df

,Posted On,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
BHK,,,,,,,,,,,
2,2022-05-18,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
2,2022-05-13,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-07-04,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
2,2022-05-09,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner
...,...,...,...,...,...,...,...,...,...,...,...
2,2022-05-18,15000,1000,3 out of 5,Carpet Area,Bandam Kommu,Hyderabad,Semi-Furnished,Bachelors/Family,2,Contact Owner
3,2022-05-15,29000,2000,1 out of 4,Super Area,"Manikonda, Hyderabad",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Owner
3,2022-07-10,35000,1750,3 out of 5,Carpet Area,"Himayath Nagar, NH 7",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Agent
3,2022-07-06,45000,1500,23 out of 34,Carpet Area,Gachibowli,Hyderabad,Semi-Furnished,Family,2,Contact Agent
2,2022-05-04,15000,1000,4 out of 5,Carpet Area,Suchitra Circle,Hyderabad,Unfurnished,Bachelors,2,Contact Owner

In [2]:
#csv:a file format used to store data
#dataframe: used for analysis and manipulation

import pandas as pd
df=pd.DataFrame({
    "Name":["ram","sita","hari"],
    "marks":[80,90,20]

},index=[101,102,103])
df

     Name  marks
101   ram     80
102  sita     90
103  hari     20

In [2]:
expenses = []

def add_expense():
    name = input("Enter expense name: ")
    amount = float(input("Enter amount: "))

    expenses.append([name, amount])
    print("Expense added!")


def view_expense():
    if len(expenses) == 0:
        print("No expenses found.")
    else:
        print("\nExpenses:")
        for e in expenses:
            print(e[0], "-", e[1])


def show_total():
    total = 0

    for e in expenses:
        total = total + e[1]

    print("Total Expense =", total)


while True:
    print("\nExpense Tracker")
    print("1. Add Expense")
    print("2. View Expenses")
    print("3. Show Total")
    print("4. Exit")

    choice = input("Enter choice: ")

    if choice == "1":
        add_expense()

    elif choice == "2":
        view_expense()

    elif choice == "3":
        show_total()

    elif choice == "4":
        print("Thank you!")
        break

    else:
        print("Invalid choice!")

Expense Tracker
1. Add Expense
2. View Expenses
3. Show Total
4. Exit
Expense added!

Expense Tracker
1. Add Expense
2. View Expenses
3. Show Total
4. Exit
Expense added!

Expense Tracker
1. Add Expense
2. View Expenses
3. Show Total
4. Exit

Expenses:
food - 100.0
water - 1000.0

Expense Tracker
1. Add Expense
2. View Expenses
3. Show Total
4. Exit
Total Expense = 1100.0

Expense Tracker
1. Add Expense
2. View Expenses
3. Show Total
4. Exit
Thank you!

In [3]:
import pandas as pd
df=pd.read_csv("House_Rent_Dataset.csv",index_col="BHK",usecols=['BHK','Area Locality'])
print(df)

                Area Locality
BHK
2                      Bandel
2    Phool Bagan, Kankurgachi
2     Salt Lake City Sector 2
2                 Dumdum Park
2               South Dum Dum
..                        ...
2                Bandam Kommu
3        Manikonda, Hyderabad
3        Himayath Nagar, NH 7
3                  Gachibowli
2             Suchitra Circle

[4746 rows x 1 columns]

In [9]:
import pandas as pd
df=pd.read_csv("House_Rent_Dataset.csv",index_col="BHK",usecols=['BHK','Area Locality'])
print(df.iloc[3:10])

                       Area Locality
BHK
2                        Dumdum Park
2                      South Dum Dum
2                        Thakurpukur
2                           Malancha
1                           Malancha
2    Palm Avenue Kolkata, Ballygunge
2                           Natunhat

In [8]:
import pandas as pd
df=pd.read_csv("House_Rent_Dataset.csv")
#print(df.iloc[3:10])
print(df.loc[1:3])

    Posted On  BHK   Rent  Size       Floor   Area Type  \
1  2022-05-13    2  20000   800  1 out of 3  Super Area
2  2022-05-16    2  17000  1000  1 out of 3  Super Area
3  2022-07-04    2  10000   800  1 out of 2  Super Area

              Area Locality     City Furnishing Status  Tenant Preferred  \
1  Phool Bagan, Kankurgachi  Kolkata    Semi-Furnished  Bachelors/Family
2   Salt Lake City Sector 2  Kolkata    Semi-Furnished  Bachelors/Family
3               Dumdum Park  Kolkata       Unfurnished  Bachelors/Family

   Bathroom Point of Contact
1         1    Contact Owner
2         1    Contact Owner
3         1    Contact Owner

In [6]:
print(df.loc[1:3])

    Posted On  BHK   Rent  Size       Floor   Area Type  \
1  2022-05-13    2  20000   800  1 out of 3  Super Area
2  2022-05-16    2  17000  1000  1 out of 3  Super Area
3  2022-07-04    2  10000   800  1 out of 2  Super Area

              Area Locality     City Furnishing Status  Tenant Preferred  \
1  Phool Bagan, Kankurgachi  Kolkata    Semi-Furnished  Bachelors/Family
2   Salt Lake City Sector 2  Kolkata    Semi-Furnished  Bachelors/Family
3               Dumdum Park  Kolkata       Unfurnished  Bachelors/Family

   Bathroom Point of Contact
1         1    Contact Owner
2         1    Contact Owner
3         1    Contact Owner

In [10]:
df['Area Locality']=="Dumsum Park"

BHK
2    False
2    False
2    False
2    False
2    False
     ...
2    False
3    False
3    False
3    False
2    False
Name: Area Locality, Length: 4746, dtype: bool

In [1]:
import pandas as pd
df=pd.read_csv("House_Rent_Dataset.csv")
df[df["Size"]<=800]

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
5,2022-04-29,2,7000,600,Ground out of 1,Super Area,Thakurpukur,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
6,2022-06-21,2,10000,700,Ground out of 4,Super Area,Malancha,Kolkata,Unfurnished,Bachelors,2,Contact Agent
7,2022-06-21,1,5000,250,1 out of 2,Super Area,Malancha,Kolkata,Unfurnished,Bachelors,1,Contact Agent
...,...,...,...,...,...,...,...,...,...,...,...,...
4724,2022-06-23,2,15000,600,2 out of 2,Carpet Area,"Nallagandla, Serilingampally",Hyderabad,Unfurnished,Bachelors,1,Contact Owner
4725,2022-05-14,1,9000,650,1 out of 3,Super Area,"Basheer Bagh, NH 7",Hyderabad,Furnished,Bachelors/Family,1,Contact Agent
4727,2022-06-28,3,30000,214,2 out of 2,Super Area,Jubilee Hills,Hyderabad,Furnished,Bachelors,4,Contact Owner
4730,2022-04-30,2,8000,600,1 out of 4,Super Area,Suraram,Hyderabad,Unfurnished,Bachelors/Family,2,Contact Owner
4733,2022-06-28,1,5000,500,Ground out of 1,Carpet Area,BN Reddy Nagar,Hyderabad,Furnished,Bachelors/Family,1,Contact Owner

In [18]:
#oops
#class is a blueprint of object which is used to create object with similar attributes,methods, behaviour.

#example:
#class: college,car,student
#object: NCCS, toyota, krisma

In [20]:
class Student:
    def __init__(self, name, age, address):
        self.name = name
        self.age = age
        self.address = address

    def display_info(self):
        print("Name:", self.name)
        print("Age:", self.age)
        print("Address:", self.address)
    #create objects
s1=Student("Ansu", 22, "Dhobidhara")
s2=Student("Krisma", 23, "Jungle")
s3=Student("Sudip", 2, "Zoo")
s1.display_info()
s2.display_info()
s3.display_info()

Name: Ansu
Age: 22
Address: Dhobidhara
Name: Krisma
Age: 23
Address: Jungle
Name: Sudip
Age: 2
Address: Zoo

In [21]:
#__init__ is a constructor. It runs automatically when an object is created. It initializes the attributes of the object.
#Student.__init__(s1,"ram",20,66):py does internally

#self: refers to current objects
#objects: real instance()
#example: ram

In [7]:
#question: Bank Account System
#create a program to manage bank account.
#acccount holder name
#types of account
#balance

#the program should:
#create multiple accounts
#deposit money
#withdraw money
#display account details
class BankAccount:
    def __init__(self, account_holder, account_type, initial_balance=0):
        self.account_holder = account_holder
        self.account_type = account_type
        self.balance = initial_balance
    
    def deposit(self, amount):
        if amount > 0:
            self.balance += amount
            return f"Deposited Rs. {amount}. New balance: Rs. {self.balance}"
        return "Amount must be positive"
    
    def withdraw(self, amount):
        if amount > 0:
            if amount <= self.balance:
                self.balance -= amount
                return f"Withdrew Rs. {amount}. New balance: Rs. {self.balance}"
            else:
                return f"Insufficient balance! You have Rs. {self.balance}"
        return "Amount must be positive"
    
    def display(self):
        return f"Holder: {self.account_holder}, Type: {self.account_type}, Balance: Rs. {self.balance}"

acc1 = BankAccount("Anshu", "Savings", 50000)
acc2 = BankAccount("Alice", "Current", 100000)

print(acc1.deposit(10000))
print(acc1.withdraw(5000))
print(acc1.display())

Deposited Rs. 10000. New balance: Rs. 60000
Withdrew Rs. 5000. New balance: Rs. 55000
Holder: Anshu, Type: Savings, Balance: Rs. 55000

In [23]:
#Advantages:
#reusability: once a class is created, it can be reused to create multiple objects.
#keeps data organized
#secure data
#add more features easily
#create unlimited users or accounts

In [ ]:
#when do we not use self?
#1) local variables

def add(self,a,b):
    result=a+b
    return result
print(add(s1,2,3))
#print(add(2,3))  # yesma self ma 2 gayera basxa ani a ma 3
 #temporary result -(no self needed for temporary results)

5

In [25]:
#2) static values
def greet(self):
     print("hello")
# no self needed inside

In [26]:
#when not to use __init__
#if no initial data needed.
class Hello:
     def greet(self):
        print("hello")

In [32]:
class student:
    def __init__(self,name,age,phone):
        self.name=name
        self.age=age
        self.phone=phone
    def display(self):
        print("Name:",self.name,"\nAge:",self.age,"\nPhone:",self.phone)
s1=student("Ansu", 22, 98497278389)
s1.display()

Name: Ansu
Age: 22
Phone: 98497278389

In [ ]:
#__str__ method
class Student:
    def __init__(self,name,age,phone):
        self.name=name
        self.age=age
        self.phone=phone
    def __str__(self):
        return f"Name:{self.name},Age:{self.age},phone:{self.phone}"
a= Student("ram",32,9378900)
print(a)
#str le string lai print garxa

Name:ram,Age:32,phone:9378900

In [36]:
#without str: this is student object stored at this memory location
#             because you did not define how to display the object
# with str: python prints your customs messages
print(f"Name":{name},age:{age},")

SyntaxError: unterminated string literal (detected at line 4) (2942406648.py, line 4)

In [ ]:
#inheritance means one class can reuse and extend another class
# A child can get properties and behaviour from a parent class
#eg:
#parent (base class)
    # person 
     #name
     #age
#child classes
#student 
#teacher

#both student and teacher have name and age(same) but also have extra features
#instead of rewriting name/age again and again , we reuse persons

In [2]:
#parent class
class Person:
    def __init_(self,name,age):
        self.name=name
        self.age=age
    def show(self):
        print("name",self.name)

In [3]:
#assignment
class Student:
    def __init__(self,name,age,gender):
        self.name=name
        self.age=age
        self.gender=gender

s1=Student("ram",32,"male")
s2=Student("sita",31,"Female")
print(s1.name)
print(s2.name)

ram
sita

In [17]:

class Student:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def display(self):
        print(f"Name: {self.name}")
        print(f"Age: {self.age}")

class Person(Student):
    def __init__(self, name, age, roll_no):
        super().__init__(name, age)   # Calls parent constructor
        self.roll_no = roll_no

    def show_student(self):
        print(f"Roll No: {self.roll_no}")

# Creating object of child class
s1 = Person("Ram", 32, 1)

s1.display()
s1.show_student()

Name: Ram
Age: 32
Roll No: 1

In [4]:
import pandas as pd
df=pd.DataFrame({
    "Name":["ram","sita","hari"],
    "marks":[80,90,20]

},index=[101,102,103])
df

     Name  marks
101   ram     80
102  sita     90
103  hari     20

In [ ]:
#df.loc[row,column]
#df.iloc[row_position,col_position]
print(df.loc[102,"marks"])
#102 is index label
#marks:column name

print(df.iloc[1,1])

#1:second row position(start count from 0)
#1:second column position

90
90

In [ ]:
import pandas as pd
df=pd.read_csv("House_Rent_Dataset.csv")
print(df[df['Area Locality']=='Malancha'])
#df['area locality]=="Malancha" -->creates t/f condition
#df[condition]-->filters row where name is  malancha

    Posted On  BHK   Rent  Size            Floor   Area Type Area Locality  \
6  2022-06-21    2  10000   700  Ground out of 4  Super Area      Malancha
7  2022-06-21    1   5000   250       1 out of 2  Super Area      Malancha

      City Furnishing Status Tenant Preferred  Bathroom Point of Contact
6  Kolkata       Unfurnished        Bachelors         2    Contact Agent
7  Kolkata       Unfurnished        Bachelors         1    Contact Agent

In [12]:
#& = and
# | = or
# ~ =not
df[(df['Size']>700)& (df["Rent"]<10000)]

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner
14,2022-05-05,3,8500,900,Ground out of 2,Carpet Area,Paschim Barisha,Kolkata,Unfurnished,Bachelors,2,Contact Owner
23,2022-06-15,3,6500,1600,Ground out of 2,Super Area,Joka,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
25,2022-05-22,2,7000,1000,1 out of 1,Super Area,Rajarhat,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
27,2022-06-25,2,6000,1000,Ground out of 3,Super Area,"Kodalia, Hooghly-Chinsurah",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
...,...,...,...,...,...,...,...,...,...,...,...,...
4692,2022-05-29,2,8000,1200,Ground out of 3,Super Area,"Beeramguda, Ramachandra Puram, NH 9",Hyderabad,Semi-Furnished,Bachelors/Family,2,Contact Owner
4701,2022-07-06,1,7500,850,3 out of 5,Carpet Area,Begumpet,Hyderabad,Semi-Furnished,Bachelors,1,Contact Agent
4705,2022-07-09,2,6000,900,Ground out of 1,Carpet Area,Rampally,Hyderabad,Unfurnished,Bachelors/Family,2,Contact Owner
4722,2022-06-10,1,8000,850,Ground out of 3,Super Area,Hyderguda,Hyderabad,Unfurnished,Bachelors/Family,1,Contact Owner
4732,2022-07-08,2,7000,900,Ground out of 2,Super Area,Vinayaka Nagar,Hyderabad,Unfurnished,Bachelors/Family,1,Contact Owner

In [21]:
#Ecommerce
class Product:
     def __init__(self, name, price):
          self.nam=name
          self.pric=price
     def display(self):
             print(f"Name: {self.nam}")
             print(f"Price: {self.pric}")
class electronics(Product):
     def __init__(self,name,price,warranty):
          super().__init__(name, price)  
          self.warr = warranty
     def show(self):
        super().display()
        print(f"Warranty: {self.warr}")
class clothing(Product):
     def __init__(self,name,price,size):
          super().__init__(name, price)  
          self.size=size
     def sow(self):
          super().display()
          print(f"Size:{self.size}")
s1= electronics("Mobile",7000,2)
s2= clothing("Pant",500,1)
s1.show()
s2.sow()

Name: Mobile
Price: 7000
Warranty: 2
Name: Pant
Price: 500
Size:1

In [22]:
#polymorphism =many forms
#the same method name behaves differently for different objects
#like: one function --->different behaviour

#real life examples:
#notification system
# (facebook,insta,tiktok)
#sms notification
#email notification
#all used to send notification

In [23]:
class Notification:
    def send (self):
        print("Sending notification...")
class Email:
    def send(self):
        print("Sending emails")
class Sms(Notification):
    def send(self):
        print("sending sms")
class Push(Notification):
    def send(self):
        print("push notification")
notification=[Email(),Sms(),Push()]
for n in notification:
    n.send()

Sending emails
sending sms
push notification

In [24]:
#same name --> different behavior
#create a shape system:
#base class: shape
#child class:circle,rectangle
#method:area() --->behaves differently

class shape:
    def area(self):
        pass
class circle(shape):
    def __init__(self,r):
        self.r=r
    def area(self):
        return 3.14* self.r*self.r
class rectangle(shape):
    def __init__(self,l,b):
        self.l=l
        self.b=b
    def area(self):
        return self.l*self.b
shapes=[circle(5),rectangle(8,9)]
for s in shapes:
    print(s.area())

78.5
72

In [ ]:
#without using super whether we can call the parent constructor or not?

#Yes,we can

#Using super
class Parent:
    def __init__(self):
        print("Parent constructor")

class Child(Parent):
    def __init__(self):
        super().__init__()
        print("Child constructor")

obj = Child()

#without using super
class Parent:
    def __init__(self):
        print("Parent constructor")

class Child(Parent):
    def __init__(self):
        Parent.__init__(self)
        print("Child constructor")

obj = Child()


#1) when you dont need parents __init__() ---> no need of super class
#2) child has its own __init--() and needs parent attributes ---> use super class

In [ ]:
#types of polymorphism
# design library system using inheritance
#base class: libraryitems
#derivedclass: book
#library item: title,author,category,price
#methods display info,apply discount,final price

In [2]:
class LibraryItem:
    def __init__(self, title, author, category, price):
        self.title = title
        self.author = author
        self.category = category
        self.price = price
    def display_info(self):
                print(f"Title: {self.title}")
                print(f"Author: {self.author}")
                print(f"Category: {self.category}")
                print(f"Price: {self.price}")
    def apply_discount(self, discount):
        self.price = self.price - (self.price * discount / 100)

    def pricee(self):
        print("Final Price:", self.price)
class Book(LibraryItem):
    def __init__(self, title, author, category, price, pages):
        super().__init__(title, author, category, price)
        self.pages = pages

    def display_info(self):
        super().display_info()
        print("Pages:", self.pages)

book1 = Book("Python", "priya", "programming", 1000, 500)
book1.display_info()
book1.apply_discount(20)
book1.pricee()

Title: Python
Author: priya
Category: programming
Price: 1000
Pages: 500
Final Price: 800.0

In [6]:
#Polymorphism means "one method, many forms."
#Types of polymorphism

#Compile-time Polymorphism :   (Method Overloading)
#             The same method is used with different parameters.
class Calculator:
    def add(self, a, b=0):
        print(a + b)
c = Calculator()

c.add(5)
c.add(5, 10)

#Runtime Polymorphism:   (Method Overriding)
#              A child class provides its own version of a method already defined in the parent class.
class Animal:
    def sound(self):
        print("Animal makes a sound")

class Dog(Animal):
    def sound(self):
        print("Dog barks")

class Cat(Animal):
    def sound(self):
        print("Cat meows")

d = Dog()
c = Cat()
d.sound()
c.sound()

5
15
Dog barks
Cat meows

In [ ]:
#overriding
#parents has a method ---> childs inherits it --> child changes the same method --->method overiding


#use super with overriding
class Person:
    def show(self):
        print("I am person")
class student(Person):
    def show(self):
        super().show()
        print('i am student')
s=student()
s.show()

i am student

In [ ]:
# 2 ta parents line ani child le 2tai ko inherit garne paryo
#ATM system
# Account(Parent)
# SavingAccount(child)
#Data types:
# public type---> account holder name
# protected--->_balance
# private ---->__pin
# mthods: deposits,withdeaw ,show_balance

In [10]:
class Account:
    def __init__(self,name,balance,pin):
        self.name=name
        self._balance=balance #protected
        self.__pin=pin #private
    def deposit(self,amount):
        self._balance+=amount
    def withdraw(self,amount):
        self._balance-=amount
    def show_balance(self):
        print("Total balance=",self._balance)
acc=Account("Anshu",50000,100)
acc.deposit(1000)
acc.withdraw(5000)
acc.show_balance()

Total balance= 46000

In [11]:
#public: evryone can access it
#protected: child
#private: only class

#eg: public (name):name can be used by anyone
#protected :bank balance: you and bank manage it
        # interact with it through deposit/withdraw methods
#private(__pin):your atm pin.cant visible and changed by outside or other

In [15]:
#protected
class BankAccount:
    def __init__(self,name,balance):
        self.name=name
        self._balance=balance
    def deposit(self,amount):
        self._balance+=amount
    def show_balance(self):
        print("balance",self._balance)
acc=BankAccount("sita",3000)
acc.deposit(200)
acc.show_balance()
print(acc._balance)

balance 3200
3200

In [5]:
class BankAccount:
    def __init__(self,name,balance,pin):
        self.name=name
        self._balance=balance
        self.__pin=pin
    def check_pin(self,entered_pin):
        if entered_pin==self.__pin:
            print("correct")
        else:
            print("incorrect pin")
acc=BankAccount("sita",3000,1234)
acc.__pin=8888
acc.check_pin(1234)
print(acc.__pin)
print(acc._BankAccount__pin)

correct
8888
1234

In [6]:
#abstraction : hide internal details and show only essential features
# use only see what to do
# advantages : reduce complexity\
# improve security
# hide sensitive logic
# make system easier to use

In [7]:
# design hospital system where
# base class : Treatment(abstract)
# child class : surgery, therapy

#each must implement
#perform_treatment()

from abc import ABC , abstractmethod

class Treatment(ABC):
    @abstractmethod
    def perform_treatment(self):
        pass

class Surgery(Treatment):
    def perform_treatment(self):
        print("Performing surgery with doctors ")

class Therapy (Treatment):

    def perform_treatment(self):
        print("Providing therapy sessions to patient")

#objects:
t1=Surgery()
t2=Therapy()
t1.perform_treatment()
t2.perform_treatment()

Performing surgery with doctors
Providing therapy sessions to patient

In [9]:
#decoraor: modifies or add behavior to a function without changing function's code
def greet():
    print ("hello")
greet()

hello

In [11]:
def my_decorator(func):
    def wrapper():
        print("before")
        func()
        print("After")
    return wrapper

In [12]:
@my_decorator
def greet():
    print ("hello")
greet()

before
hello
After

In [13]:
from abc import ABC , abstractmethod
class Shape(ABC):

    @abstractmethod
    def area(self):
        pass
class Rectangle(Shape):
    def __init__(self, length, width):
        self.length = length
        self.width = width

    def area(self):
        return self.length * self.width
r = Rectangle(5, 4)
print("Rectangle Area:", r.area())

Rectangle Area: 20

In [2]:
# 2 ta parents line ani child le 2tai ko inherit garna paryo
class Person:
    def __init__(self,name,id):
        self.name=name
        self.id=id
    def show(self):
        print(f"Name : {self.name}\nID : {self.id}")
class Employee():
    def __init__(self,salary):
        self.salary=salary
    def show(self):
        print(f"Salary : {self.salary}")
class Manager(Person,Employee):
    def __init__(self,name,id,salary,experience):
        Person.__init__(self,name,id)
        Employee.__init__(self,salary)
        self.experience=experience
    def show(self):
        Person.show(self)
        Employee.show(self)
        print(f"Experience : {self.experience} yrs")

M = Manager("ram",101,50000,3)
M.show()

Name : ram
ID : 101
Salary : 50000
Experience : 3 yrs

In [ ]:
import matplotlib.pyplot as plt

subjects=['Maths','Science','English','History','Geography']
marks=[85,90,78,88,92]

plt.figure(figsize=(10,5))

plt.bar(subjects, marks, color='skyblue')

plt.xlabel('Subjects')
plt.ylabel('Marks')
plt.title('Student Marks in Different Subjects')